name: todo_modular
version: 1.0.0+1
description: Modular Flutter Todo App with modern UI, Pomodoro, and CI/CD.

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  intl: ^0.18.0
  file_picker: ^6.1.1
  home_widget: ^0.5.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  csv: ^5.1.1
  audioplayers: ^5.2.1
  table_calendar: ^3.0.9
  fl_chart: ^0.65.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/empty.png
    - assets/alarm.mp3
    - lib/assets/icons/add.png
    - lib/assets/icons/delete.png
    - lib/assets/icons/timer.png
    - assets/